### ISSUE TITLE
调用芝麻认证URL接口 页面提示系统错误

### ISSUE THREAD

**Issue by zlei1** [zhchsf/zhima#1]
![image](https://user-images.githubusercontent.com/17946081/29263569-05e8998e-810c-11e7-9e97-0dbd91592bc9.png)

**Comment by zhchsf** [comment]
hello 光看图看不出来什么情况，建议检查下秘钥的正确性及是否pkcs8格式；再console中调用下看看生成的地址等。目前改gem在我们的生产环境稳定运行了快1年了

**Comment by zlei1** [comment]
@zhchsf 不好意思 最近才接触到公钥私钥的概念 我生成的公钥私钥 是使用ruby提供的openssl的库 OpenSSL::PKey::RSA.new 1024 生成的,生成的应该是pkcs #1格式的 ,请问芝麻信用是必须要pkcs8的秘钥吗，在此之前做了支付宝服务号的授权生成的公私钥是没有问题的。

**Comment by zhchsf** [comment]
可以看下官方的  https://b.zmxy.com.cn/technology/openDoc.htm?relInfo=RSA_INFO_DOC

**Comment by zlei1** [comment]
@zhchsf 好的，我自己在试试。感谢解答
